name: bussy
description: For getting bus times not annoyingly
version: 1.0.0

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
